CREATE TABLE IF NOT EXISTS todos (
  id CHAR(36) NOT NULL,
  text VARCHAR(200) NOT NULL,
  categorie VARCHAR(20) NULL,
  date_limite DATE NULL,
  completed TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);